swagger: "2.0"
info:
  title: main-gateway Reviews API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /aadvanced:
    get:
      summary: Anna's advanced query
      operationId: aadvanced
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-aadvanced
      responses:
        200:
          description: OK
  /call-procedure:
    get:
      summary: Call stored procedure
      operationId: callProcedure
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-call-procedure
      responses:
        200:
          description: OK
  /create-product:
    post:
      summary: Create a product
      operationId: createProduct
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-create-product
      responses:
        201:
          description: Product created
  /create-profile:
    post:
      summary: Create the specified user profile
      operationId: createProfile
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-create-profile
      responses:
        201:
          description: Profile created
  /delete-product:
    delete:
      summary: Deletes the product if it exists
      operationId: deleteProduct
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-delete-product
      responses:
        200:
          description: Product deleted
  /delete-profile:
    delete:
      summary: Deletes the profile if it exists
      operationId: deleteProfile
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-delete-profile
      responses:
        200:
          description: Profile deleted
  /edit-profile:
    post:
      summary: Edits the profile if it exists
      operationId: editProfile
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-edit-profile
      responses:
        200:
          description: Profile edited
  /filter-product:
    get:
      summary: Returns products filtered
      operationId: filterProduct
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-filter-product
      responses:
        200:
          description: OK
  /get-ingredient:
    get:
      summary: Returns ingredient by search term
      operationId: getIngredient
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-ingredient
      responses:
        200:
          description: OK
  /get-ingredient-all:
    get:
      summary: Returns ingredient by search term
      operationId: getIngredientAll
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-ingredient-all
      responses:
        200:
          description: OK
  /get-product-all:
    get:
      summary: Returns all products
      operationId: getProductAll
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-product-all
      responses:
        200:
          description: OK
  /get-profile:
    get:
      summary: Returns the specified user profile
      operationId: getProfile
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-profile
      responses:
        200:
          description: OK
  /get-review-all:
    get:
      summary: Returns all reviews
      operationId: getReviewAll
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-review-all
      responses:
        200:
          description: OK
  /get-review-username:
    get:
      summary: Returns all reviews
      operationId: getReviewUsername
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-review-username
      responses:
        200:
          description: OK
  /hadvanced:
    get:
      summary: Hannah's advanced query
      operationId: hadvanced
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-hadvanced
      responses:
        200:
          description: OK
  /ingredients:
    post:
      summary: Create the ingredient
      operationId: createIngredient
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-create-ingredient
      responses:
        201:
          description: Ingredient created
    delete:
      summary: Deletes the Ingredient if it exists
      operationId: deleteIngredient
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-delete-ingredient
      responses:
        200:
          description: Ingredient deleted
  /ingredients/edit:
    post:
      summary: Edits the ingredient
      operationId: editIngredient
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-edit-ingredient
      responses:
        200:
          description: Ingredient edited
  /reviews:
    post:
      summary: Create a review
      operationId: createReview
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-create-review
      responses:
        201:
          description: Review created
    delete:
      summary: Deletes the review if it exists
      operationId: deleteReview
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-delete-review
      responses:
        200:
          description: Review deleted
  /reviews/product:
    get:
      summary: Returns the specified user review
      operationId: getReviewKey
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-review-key
      responses:
        200:
          description: OK
  /reviews/text:
    get:
      summary: Returns the specified user review
      operationId: getReviewText
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-get-review-text
      responses:
        200:
          description: OK
  /reviews/update:
    put:
      summary: Updates the review if it exists
      operationId: updateReview
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-update-review
      responses:
        200:
          description: Review updated
  /reviews-adv-query:
    get:
      summary: Returns advanced query of reviews.
      operationId: getAdvQuery
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-user-adv-query
      responses:
        200:
          description: OK
  /update-ingredient:
    post:
      summary: Updates the Ingredient if it exists
      operationId: updateIngredient
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-update-ingredient
      responses:
        200:
          description: Ingredient updated
  /update-product:
    post:
      summary: Updates the Product if it exists
      operationId: updateProduct
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-update-product
      responses:
        200:
          description: Product updated
  /user-search:
    get:
      summary: Returns users that match search query
      operationId: searchUsers
      x-google-backend:
        address: https://us-central1-ice-cream-project-308820.cloudfunctions.net/function-user-search
      responses:
        200:
          description: OK
