swagger: "2.0"
info:
  title: main-gateway Reviews API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /reviews:
    get:
      summary: Returns a list of reviews.
      operationId: getReviews
      x-google-backend:
        address: https://us-central1-test-sql-project-305022.cloudfunctions.net/function-test
      responses:
        200:
          description: OK
